version: '3'

services:
  thph-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thph-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
